# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2c684d749e9d7f978c770a8c561befda"
application_url = "https://fumiya-shop-5f616ecce0ca.herokuapp.com"
embedded = true
name = "fumiya-shop"
handle = "fumiya-shop"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://fumiya-shop-5f616ecce0ca.herokuapp.com/auth/callback",
  "https://fumiya-shop-5f616ecce0ca.herokuapp.com/auth/shopify/callback",
  "https://fumiya-shop-5f616ecce0ca.herokuapp.com/api/auth/callback"
]

[pos]
embedded = false
