# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2d68e2aa756268c482be8da0b5029207"
application_url = "https://fumiya-shop.herokuapp.com"
embedded = true
name = "fumiya-shop"
handle = "fumiya-shop"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://fumiya-shop.herokuapp.com/auth/callback",
  "https://fumiya-shop.herokuapp.com/auth/shopify/callback",
  "https://fumiya-shop.herokuapp.com/api/auth/callback"
]

[pos]
embedded = false
